# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # Python 3.9 is on macos-13 but not macos-latest (macos-14-arm64)
        # https://github.com/actions/setup-python/issues/696#issuecomment-1637587760
        exclude:
        - { python-version: "3.8", os: "macos-latest" }
        - { python-version: "3.9", os: "macos-latest" }
        include:
        - { python-version: "3.8", os: "macos-13" }
        - { python-version: "3.9", os: "macos-13" }

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        python -m pip install .[tests]
    - name: Lint with flake8
      run: |
        flake8 examples tests pyriemann setup.py
    - name: Test with pytest
      run: |
        pytest
